# Generated by Django 4.0.4 on 2022-05-19 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_user_address_user_age_user_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadharno', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('telephone_number', models.CharField(max_length=15)),
                ('emailid', models.EmailField(max_length=200)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlightDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(max_length=200)),
                ('airline_name', models.CharField(max_length=200)),
                ('source_airport', models.CharField(max_length=200)),
                ('destination_airport', models.CharField(max_length=200)),
                ('source_state', models.CharField(max_length=200)),
                ('destination_state', models.CharField(max_length=200)),
                ('flight_duration', models.CharField(max_length=200)),
                ('stops', models.CharField(max_length=200)),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('remaining_seats', models.IntegerField()),
                ('total_seats', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('trip_date', models.DateField()),
                ('num_of_passengers', models.CharField(max_length=200)),
                ('total_price', models.CharField(max_length=200)),
                ('booking_time', models.TimeField(auto_now=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.flightdetails')),
                ('passenger', models.ManyToManyField(to='users.passenger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
