# Generated by Django 4.0.4 on 2022-05-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='booking_date',
            field=models.DateField(auto_now=True),
        ),
    ]
