# Generated by Django 4.0.4 on 2022-05-23 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('address', models.TextField(default=' ', max_length=200)),
                ('contact', models.CharField(default=' ', max_length=15)),
                ('gender', models.CharField(default=' ', max_length=100)),
                ('city', models.CharField(default=' ', max_length=200)),
                ('age', models.CharField(default=' ', max_length=100)),
                ('state', models.CharField(default=' ', max_length=200)),
                ('country', models.CharField(default=' ', max_length=200)),
                ('pincode', models.CharField(default=' ', max_length=20)),
                ('date_of_birth', models.DateTimeField(null=True)),
                ('permission', models.CharField(default=' ', max_length=200)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadharno', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('telephone_number', models.CharField(max_length=15)),
                ('emailid', models.EmailField(max_length=200)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlightDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(max_length=200)),
                ('airline_name', models.CharField(max_length=200)),
                ('source_airport', models.CharField(max_length=200)),
                ('destination_airport', models.CharField(max_length=200)),
                ('source_state', models.CharField(max_length=200)),
                ('destination_state', models.CharField(max_length=200)),
                ('flight_duration', models.CharField(max_length=200)),
                ('stops', models.CharField(max_length=200)),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('remaining_seats', models.IntegerField()),
                ('total_seats', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now=True)),
                ('trip_date', models.DateField()),
                ('num_of_passengers', models.CharField(max_length=200)),
                ('total_price', models.CharField(max_length=200)),
                ('booking_time', models.TimeField(auto_now=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.flightdetails')),
                ('passenger', models.ManyToManyField(to='apis.passenger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
