# Generated by Django 4.0.4 on 2022-07-27 06:48

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightdetails',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='flight_name', unique_with=('airport__name',)),
        ),
    ]
