# Generated by Django 4.0.4 on 2022-07-27 06:52

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_flightdetails_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightdetails',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=True, populate_from='flight_name', unique_with=('airport__name',)),
        ),
    ]
